# fly.toml app configuration file generated for weatherman-h-t-1-1718967448-server on 2024-06-21T10:58:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weatherman-h-t-1-1718967448-server'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
